<a href="https://colab.research.google.com/github/ingridcos/Desafio-SQL-1/blob/main/Desafio_Pipeline_de_ETL_Integrado_Semana_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Desafio Pipeline ETL Integrado [WoMarkersCode]**

## **Ingrid Costa Ferreira**

###1.1 - Instalação e Importação

In [1]:
!pip install pandas prefect dbt-sqlite requests -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 kB 3.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.4/114.4 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 48.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 65.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 71.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.5/315.5 kB 21.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.7/167.7 kB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 986.2/986.2 kB 48.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.7/150.7 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 351.2/351.2 kB 20.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.9/119.9 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.0/22.0 MB 87.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.9/144.9 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.4/87.4 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.7/442.7 kB 22.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.1/160.1 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.0/147.0 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.0/119.0 kB 7.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.2/92.2 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.3/323.3 kB 18.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.3/96.3 kB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.2/354.2 kB 24.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 788.2/788.2 kB 40.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.4/91.4 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 67.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.4/132.4 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 220.0/220.0 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 2.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-otlp-proto-http 1.37.0 requires opentelemetry-sdk~=1.37.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.2 which is incompatible.
google-adk 1.20.0 requires opentelemetry-api<=1.37.0,>=1.37.0, but you have opentelemetry-api 1.39.0 which is incompatible.
google-adk 1.20.0 requires opentelemetry-sdk<=1.37.0,>=1.37.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 6.33.2 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.2 which is incompatible.

In [2]:
import sys
!{sys.executable} -m pip install "protobuf>=3.20.3,<6.0.0dev" --force-reinstall
!{sys.executable} -m pip install "opentelemetry-sdk~=1.37.0" "opentelemetry-api~=1.37.0" --force-reinstall
!{sys.executable} -m pip check

Collecting protobuf<6.0.0dev,>=3.20.3
  Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Downloading protobuf-5.29.5-cp38-abi3-manylinux2014_x86_64.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.9/319.9 kB 6.6 MB/s eta 0:00:00
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.33.2
    Uninstalling protobuf-6.33.2:
      Successfully uninstalled protobuf-6.33.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dbt-common 1.36.0 requires protobuf<7.0,>=6.0, but you have protobuf 5.29.5 which is incompatible.
dbt-adapters 1.16.7 requires protobuf<7.0,>=6.0, but you have protobuf 5.29.5 which is incompatible.
dbt-core 1.10.15 requires protobuf<7.0,>=6.0, but you have protobuf 5.29.5 which is incompatible.
google-adk 1.20.0 requires opentelemetry-api<=1.37.0,>=1.37.0, but you have opentelemetry-api 1.39.0 which is incompatible.
google-adk 1.20.0 requires opentelemetry-sdk<=1.37.0,>=1.37.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
Successfully installed protobuf-5.29.5
Collecting opentelemetry-sdk~=1.37.0
  Downloading opentelemetry_sdk-1.37.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-api~=1.37.0
  Downloading opentelemetry_api-1.37.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-semantic-conventions==0.58b0 (from opentelemetry-sdk~=1.37.0)
  Downloading opentelemetry_semantic_conventions-0.58b0-py3-none-any.whl.metadata (2.4 kB)
Collecting typing-extensions>=4.5.0 (from opentelemetry-sdk~=1.37.0)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting importlib-metadata<8.8.0,>=6.0 (from opentelemetry-api~=1.37.0)
  Downloading importlib_metadata-8.7.0-py3-none-any.whl.metadata (4.8 kB)
Collecting zipp>=3.20 (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api~=1.37.0)
  Downloading zipp-3.23.0-py3-none-any.whl.metadata (3.6 kB)
Downloading opentelemetry_sdk-1.37.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.9/131.9 kB 9.8 MB/s eta 0:00:00
Downloading opentelemetry_api-1.37.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.7/65.7 kB 4.6 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.58b0-py3-none-any.whl (207 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.0/208.0 kB 15.9 MB/s eta 0:00:00
Downloading importlib_metadata-8.7.0-py3-none-any.whl (27 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 2.4 MB/s eta 0:00:00
Downloading zipp-3.23.0-py3-none-any.whl (10 kB)
Installing collected packages: zipp, typing-extensions, importlib-metadata, opentelemetry-api, opentelemetry-semantic-conventions, opentelemetry-sdk
  Attempting uninstall: zipp
    Found existing installation: zipp 3.23.0
    Uninstalling zipp-3.23.0:
      Successfully uninstalled zipp-3.23.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.15.0
    Uninstalling typing_extensions-4.15.0:
      Successfully uninstalled typing_extensions-4.15.0
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib_metadata 8.7.0
    Uninstalling importlib_metadata-8.7.0:
      Successfully uninstalled importlib_metadata-8.7.0
  Attempting uninstall: opentelemetry-api
    Found existing installation: opentelemetry-api 1.39.0
    Uninstalling opentelemetry-api-1.39.0:
      Successfully uninstalled opentelemetry-api-1.39.0
  Attempting uninstall: opentelemetry-semantic-conventions
    Found existing installation: opentelemetry-semantic-conventions 0.60b0
    Uninstalling opentelemetry-semantic-conventions-0.60b0:
      Successfully uninstalled opentelemetry-semantic-conventions-0.60b0
  Attempting uninstall: opentelemetry-sdk
    Found existing installation: opentelemetry-sdk 1.39.0
    Uninstalling opentelemetry-sdk-1.39.0:
      Successfully uninstalled opentelemetry-sdk-1.39.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-prometheus 0.60b0 requires opentelemetry-sdk~=1.39.0, but you have opentelemetry-sdk 1.37.0 which is incompatible.
dbt-common 1.36.0 requires protobuf<7.0,>=6.0, but you have protobuf 5.29.5 which is incompatible.
dbt-adapters 1.16.7 requires protobuf<7.0,>=6.0, but you have protobuf 5.29.5 which is incompatible.
dbt-core 1.10.15 requires protobuf<7.0,>=6.0, but you have protobuf 5.29.5 which is incompatible.
Successfully installed importlib-metadata-8.7.0 opentelemetry-api-1.37.0 opentelemetry-sdk-1.37.0 opentelemetry-semantic-conventions-0.58b0 typing-extensions-4.15.0 zipp-3.23.0
ipython 7.34.0 requires jedi, which is not installed.
opentelemetry-exporter-prometheus 0.60b0 has requirement opentelemetry-sdk~=1.39.0, but you have opentelemetry-sdk 1.37.0.
dbt-common 1.36.0 has requirement protobuf<7.0,>=6.0, but you have protobuf 5.29.5.
dbt-adapters 1.16.7 has requirement protobuf<7.0,>=6.0, but you have protobuf 5.29.5.
dbt-core 1.10.15 has requirement protobuf<7.0,>=6.0, but you have protobuf 5.29.5.

In [3]:
pip install "protobuf>=6.0,<7.0" --force-reinstall

Collecting protobuf<7.0,>=6.0
  Using cached protobuf-6.33.2-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Using cached protobuf-6.33.2-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.5
    Uninstalling protobuf-5.29.5:
      Successfully uninstalled protobuf-5.29.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 6.33.2 which is incompatible.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, but you have protobuf 6.33.2 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 6.33.2 which is incompatible.
Successfully installed protobuf-6.33.2

In [38]:
import pandas as pd
import requests
import json
import sqlite3

print("Ambiente configurado com sucesso!")

Ambiente configurado com sucesso!

###1.2 - Fonte de Dados `SQL`

In [5]:
conn_bootcamp = sqlite3.connect("bootcampBI.db")
cursor_bootcamp = conn_bootcamp.cursor()

cursor_bootcamp.execute("""
CREATE TABLE IF NOT EXISTS PARTICIPANTES (
    ID_PARTICIPANTE INT,
    NOME VARCHAR(150),
    PAIS_ORIGEM VARCHAR(100)
)
""")

participantes = [
    (1,  'Maria',    'Brasil'),
    (2,  'Luana',    'Portugal'),
    (3,  'Camila',   'Brasil'),
    (4,  'Luiza',    'Argentina'),
    (5,  'Silvia',   'Colombia'),
    (6,  'Paola',    'Brasil'),
    (7,  'Vitoria',  'Mexico'),
    (8,  'Caroline', 'Argentina'),
    (9,  'Marta',    'Portugal'),
    (10, 'Ana',      'Brasil')
]

cursor_bootcamp.executemany(
    "INSERT INTO PARTICIPANTES VALUES (?, ?, ?)",
    participantes
)

conn_bootcamp.commit()
conn_bootcamp.close()

print("Banco de Dados e tabela criados com sucesso!")

Banco de Dados e tabela criados com sucesso!

###1.3 - Fonte de Dados `JSON`

In [6]:
%%writefile habilidades_categorias.json
{
    "Ferramentas de Análise": ["Python", "R", "SQL"],
    "Ferramentas de BI": ["Power BI", "Tableau", "Looker"],
    "Plataformas de Nuvem": ["AWS", "Google Cloud", "Microsoft Azure"]
}

Overwriting habilidades_categorias.json

###1.4 - Data Warehouse

In [7]:
conn_datawarehouse = sqlite3.connect('data_warehouse.db')
conn_datawarehouse.close()

print("Data Warehouse criado com sucesso!")

Data Warehouse criado com sucesso!

##**2. Extração e Carregamento - `CSV` e `SQL`**

###2.1 - Configuração do Logger

In [8]:
import logging

In [9]:
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename='pipeline.log',
    filemode='w'
)

logger = logging.getLogger()

print("Logging configurado com sucesso!")

Logging configurado com sucesso!

In [10]:
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename='pipeline.log',
    filemode='w'
)

logger = logging.getLogger()

print("Logging configurado com sucesso!")

Logging configurado com sucesso!

###2.2 - Extração de dados de um Arquivo `CSV`

In [11]:
def extrair_dados_kaggle(caminho_arquivo):
  try:
    logger.info(f"Inicando a extração do arquivo: {caminho_arquivo}")

    df = pd.read_csv(caminho_arquivo)

    logger.info(f"Extração do CSV concluída. {len(df)} linhas lidas e {len(df.columns)} colunas.")

    # Boa prática para verificar os tipos de dados que o Pandas encontrou
    logger.info(f"Tipos de dados das colunas: \n{df.dtypes}")

    return df

  except FileNotFoundError:
    logger.error(f"Arquivo não encontrado: {caminho_arquivo}")
    return None
  except Exception as e:
    logger.error(f"Ocorreu um erro inesperado ao extrair os dados: {e}")
    return None

#Teste da função
df_kaggle = extrair_dados_kaggle("kaggle_survey_2022_mulheres_dados.csv")

if df_kaggle is not None:
  display(df_kaggle.head())

,idade,genero,pais,nivel_educacional,anos_programando,cargo_atual,anos_usando_ml,salario_anual_usd,linguagens_usadas,bancos_de_dados_usados,ferramentas_bi_usadas
0,30-34,Woman,Pakistan,Professional doctorate,5-10 years,Data Scientist,Other,NaN,NaN,NaN,NaN
1,35-39,Woman,Nigeria,Master’s degree,< 1 years,"Data Analyst (Business, Marketing, Financial, ...",Non-profit/Service,$0-999,Python;R;SQL,NaN,NaN
2,25-29,Woman,Germany,Bachelor’s degree,3-5 years,"Data Analyst (Business, Marketing, Financial, ...",Computers/Technology,$0-999,Python;SQL,NaN,NaN
3,30-34,Woman,Tunisia,Master’s degree,< 1 years,Data Scientist,Academics/Education,$0-999,Python,NaN,NaN
4,45-49,Woman,Egypt,Doctoral degree,10-20 years,Data Administrator,Computers/Technology,"10,000-14,999",Python;SQL,PostgreSQL;SQLite;Oracle Database;Snowflake,Qlik Sense

###2.3 - Extração de Dados de um Banco `SQL`

In [12]:
def extrair_dados_sql(caminho_banco):
  try:
    logger.info(f"Inicando a extração do banco de dados: {caminho_banco}")

    conexao = sqlite3.connect(caminho_banco)

    query = "SELECT * FROM PARTICIPANTES"

    df = pd.read_sql_query(query, conexao)

    logger.info(f"Extração do banco de dados concluída com sucesso!")
    return df

  except sqlite3.Error as e:
    logger.error(f"Ocorreu um erro ao conectar ao banco de dados")
    return None
  except Exception as e:
    logger.error(f"Ocorreu um erro inesperado ao extrair os dados: {e}")
    return None

  # O finally garante que a conexão com o banco seja sempre fechada, mesmo se der erro
  finally:
    if conexao:
      conexao.close()
      logger.info("Conexão com o banco de dados fechada.")

#Teste da função
df_participantes = extrair_dados_sql("bootcampBI.db")

if df_participantes is not None:
  display(df_participantes.head())

   ID_PARTICIPANTE    NOME PAIS_ORIGEM
0                1   Maria      Brasil
1                2   Luana    Portugal
2                3  Camila      Brasil
3                4   Luiza   Argentina
4                5  Silvia    Colombia

###2.4 - Função de Carregamento dos Dados

In [13]:
def carregar_dados(df, nome_tabela, caminho_dw):
  if df is None:
    logger.warning("DataFrame vazio. Nada a ser carregado.")
    return

  try:
    logger.info(f"Iniciando o carregamento dos dados na tabela: {nome_tabela}")

    conexao_dw = sqlite3.connect(caminho_dw)

    df.to_sql(nome_tabela, conexao_dw, if_exists='replace', index=False)

    logger.info(f"Carga para a tabela '{nome_tabela}' concluída com sucesso!")

  except Exception as e:
      logger.error(f"Ocorreu um erro ao carregar os dados para a tabela '{nome_tabela}': {e}")

  finally:
    if conexao_dw:
      conexao_dw.close()
      logger.info("Conexão com o Data Warehouse fechada.")

Executa a carga dos DataFrames extraídos

In [14]:
carregar_dados(df_kaggle, "kaggle_survey_2022_mulheres_dados", "data_warehouse.db")
carregar_dados(df_participantes, "participantes", "data_warehouse.db")

##**3.Extração e Carregamento - `API` e `JSON`**

###3.1 -  Extração de Dados de uma API Web

In [15]:
def extrair_dados_paises_api(url_api):
  try:
    logger.info(f"Iniciando a requisição à API: {url_api}")

    resposta = requests.get(url_api)

    if resposta.status_code == 200:
      dados_json = resposta.json()
      logger.info(f"Dados da API extraídos com sucessos. {len(dados_json)} registros de países.")
      return dados_json
    else:
      logger.error(f"Falha na requisição à API. Código de status: {resposta.status_code}")
      return None

  except Exception as e:
      logger.error(f"Ocorreu um erro inesperado ao extrair os dados")
      return None

url_paises = "https://restcountries.com/v3.1/all?fields=name,cca3,region"

#Teste da função
dados_paises = extrair_dados_paises_api(url_paises)

if dados_paises is not None:
  df_paises = pd.json_normalize(dados_paises)
  display(df_paises.head())

,cca3,region,name.common,name.official,name.nativeName.eng.official,name.nativeName.eng.common,name.nativeName.dzo.official,name.nativeName.dzo.common,name.nativeName.ita.official,name.nativeName.ita.common,...,name.nativeName.ind.official,name.nativeName.ind.common,name.nativeName.fil.official,name.nativeName.fil.common,name.nativeName.hun.official,name.nativeName.hun.common,name.nativeName.nep.official,name.nativeName.nep.common,name.nativeName.khm.official,name.nativeName.khm.common
0,ATG,Americas,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,Antigua and Barbuda,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BTN,Asia,Bhutan,Kingdom of Bhutan,NaN,NaN,འབྲུག་རྒྱལ་ཁབ་,འབྲུག་ཡུལ་,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ITA,Europe,Italy,Italian Republic,NaN,NaN,NaN,NaN,Repubblica italiana,Italia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TUV,Oceania,Tuvalu,Tuvalu,Tuvalu,Tuvalu,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AIA,Americas,Anguilla,Anguilla,Anguilla,Anguilla,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###3.2 - Extração de `JSON` (Simulando `NoSQL`) e Preparação para Transformação

In [16]:
def extrair_categorias_habilidades_json(caminho_arquivo):
  try:
    logger.info(f"Iniciando a extração do arquivo JSON: {caminho_arquivo}")

    with open(caminho_arquivo, 'r') as arquivo:
      dados_json = json.load(arquivo)

    logger.info("Extração do JSON concluída com sucesso!")
    return dados_json

  except FileNotFoundError:
    logger.error(f"Arquivo não encontrado: {caminho_arquivo}")
    return None
  except Exception as e:
    logger.error(f"Ocorreu um erro inesperado ao extrair os dados: {e}")
    return None

#Teste da função
dados_habilidades = extrair_categorias_habilidades_json("habilidades_categorias.json")

if dados_habilidades is not None:
  df_habilidades = pd.json_normalize(dados_habilidades)
  display(df_habilidades.head())

,Ferramentas de Análise,Ferramentas de BI,Plataformas de Nuvem
0,"[Python, R, SQL]","[Power BI, Tableau, Looker]","[AWS, Google Cloud, Microsoft Azure]"

###3.3 - Tabulação do `JSON`

In [17]:
def transformar_json_em_df(dados_json):
  if dados_json is None:
    logger.warning("Dados JSON vazios. Nada a ser transformado")
    return None

  lista_categorias = []

  for categoria, habilidades in dados_json.items():
    for habilidade in habilidades:
      lista_categorias.append({"CATEGORIA": categoria, "HABILIDADE" : habilidade})

  df_categorias = pd.DataFrame(lista_categorias)

  logger.info("Transformação do JSON em DataFrame concluída com sucesso!")
  return df_categorias

#Teste da função
df_categorias = transformar_json_em_df(dados_habilidades)

if df_categorias is not None:
  display(df_categorias.head())

                CATEGORIA HABILIDADE
0  Ferramentas de Análise     Python
1  Ferramentas de Análise          R
2  Ferramentas de Análise        SQL
3       Ferramentas de BI   Power BI
4       Ferramentas de BI    Tableau

 Carregamento dos DataFrames

In [18]:
carregar_dados(df_paises, "paises", "data_warehouse.db")
carregar_dados(df_categorias, "categorias", "data_warehouse.db")

##**4. Transformação com dbt**

###4.1 Criação do projeto dbt

In [19]:
!dbt init pipeline_mulheres_na_tecnologia

19:32:04  Running with dbt=1.10.15
19:32:05  Creating dbt configuration folder at /root/.dbt
19:32:05
Your new dbt project "pipeline_mulheres_na_tecnologia" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

19:32:05  Setting up your profile.
Which database would you like to use?
[1] sqlite

(Don't see the one you want? https://docs.getdbt.com/docs/available-adapters)

Enter a number: 1
19:33:19  Profile pipeline_mulheres_na_tecnologia written to /root/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.

###4.2 Configuração do arquivo profiles.yml

In [20]:
import yaml
import os

In [21]:
profiles_config = {
    'pipeline_mulheres_na_tecnologia': {
        'target': 'dev',
        'outputs': {
            'dev': {
                'type': 'sqlite',
                'threads': 1,

                # Parâmetro para versões mais recentes
                'schemas_and_paths': {
                    'main': '../data_warehouse.db'
                },

                # Parâmetro para versões mais antigas
                'database': '../data_warehouse.db',

                # Parâmetro para versões mais antigas
                'schema': 'main',

                # Parâmetro opcional, mas boa prática
                'schema_directory': '.'
            }
        }
    }
}

# Caminho onde o dbt espera encontrar o arquivo de perfis
dbt_profile_dir = os.path.expanduser('~/.dbt/')
os.makedirs(dbt_profile_dir, exist_ok=True)
profiles_path = os.path.join(dbt_profile_dir, 'profiles.yml')

with open(profiles_path, 'w') as f:
    yaml.dump(profiles_config, f)

###4.3 Testando a conexão

In [22]:
%cd pipeline_mulheres_na_tecnologia
!dbt debug

/content/pipeline_mulheres_na_tecnologia
19:33:25  Running with dbt=1.10.15
19:33:25  dbt version: 1.10.15
19:33:25  python version: 3.12.12
19:33:25  python path: /usr/bin/python3
19:33:25  os info: Linux-6.6.105+-x86_64-with-glibc2.35
19:33:25  Using profiles dir at /root/.dbt
19:33:25  Using profiles.yml file at /root/.dbt/profiles.yml
19:33:25  Using dbt_project.yml file at /content/pipeline_mulheres_na_tecnologia/dbt_project.yml
19:33:25  adapter type: sqlite
19:33:25  adapter version: 1.10.0
19:33:26  Configuration:
19:33:26    profiles.yml file [OK found and valid]
19:33:26    dbt_project.yml file [OK found and valid]
19:33:26  Required dependencies:
19:33:26   - git [OK found]

19:33:26  Connection:
19:33:26    database: ../data_warehouse.db
19:33:26    schema: main
19:33:26    schemas_and_paths: {'main': '../data_warehouse.db'}
19:33:26    schema_directory: .
19:33:26  Registered adapter: sqlite=1.10.0
19:33:26    Connection test: [OK connection ok]

19:33:26  All checks passed!

##**5. Criando Modelos de *Staging* com dbt**

###5.1 Configurando as Fontes

In [26]:
%%writefile /content/pipeline_mulheres_na_tecnologia/models/staging/source.yml
version: 2

sources:
  - name: dados_brutos
    database: data_warehouse.db
    schema: main

    tables:
      - name: kaggle_survey_2022_mulheres_dados
        description: "Dados brutos da pesquisa Kaggle, filtrado por mulheres na área de dados"
      - name: participantes
        description: "Dados das participantes do bootcamp"
      - name: paises
        description: "Dados dos países extraídos da API REST Countries"
      - name: categorias
        description: "Mapeamento das habilidades e categorias, extraído de um arquivo JSON"

Overwriting /content/pipeline_mulheres_na_tecnologia/models/staging/source.yml

###5.2 Criando o Primeiro Modelo de Staging

In [27]:
%%writefile /content/pipeline_mulheres_na_tecnologia/models/staging/stg_kaggle_survey_2022_mulheres_dados.sql
SELECT PAIS,
    NIVEL_EDUCACIONAL,
    ANOS_PROGRAMANDO,
    CARGO_ATUAL,
    ANOS_USANDO_ML,
    CASE WHEN SALARIO_ANUAL_USD LIKE '%-%'
         THEN CAST(REPLACE(SUBSTR(SALARIO_ANUAL_USD, 1, INSTR(SALARIO_ANUAL_USD, '-') - 1),',','') AS REAL)
         WHEN SALARIO_ANUAL_USD IS NOT NULL
         THEN CAST(REPLACE(SALARIO_ANUAL_USD, ',', '') AS REAL)
         ELSE NULL
    END AS SALARIO_ANUAL_USD,
    LINGUAGENS_USADAS,
    BANCOS_DE_DADOS_USADOS,
    FERRAMENTAS_BI_USADAS
FROM {{ source('dados_brutos', 'kaggle_survey_2022_mulheres_dados') }}

Overwriting /content/pipeline_mulheres_na_tecnologia/models/staging/stg_kaggle_survey_2022_mulheres_dados.sql

In [28]:
!dbt run

19:37:49  Running with dbt=1.10.15
19:37:49  Registered adapter: sqlite=1.10.0
19:37:49  Unable to do partial parsing because saved manifest not found. Starting full parse.
19:37:51  Found 3 models, 4 data tests, 4 sources, 416 macros
19:37:51
19:37:51  Concurrency: 1 threads (target='dev')
19:37:51
19:37:52  1 of 3 START sql table model main.my_first_dbt_model ........................... [RUN]
19:37:52  1 of 3 OK created sql table model main.my_first_dbt_model ...................... [OK in 0.07s]
19:37:52  2 of 3 START sql view model main.stg_kaggle_survey_2022_mulheres_dados ......... [RUN]
19:37:52  2 of 3 OK created sql view model main.stg_kaggle_survey_2022_mulheres_dados .... [OK in 0.05s]
19:37:52  3 of 3 START sql view model main.my_second_dbt_model ........................... [RUN]
19:37:52  3 of 3 OK created sql view model main.my_second_dbt_model ...................... [OK in 0.03s]
19:37:52
19:37:52  Finished running 1 table model, 2 view models in 0 hours 0 minutes and 0.27 seconds (0.27s).
19:37:52
19:37:52  Completed successfully
19:37:52
19:37:52  Done. PASS=3 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=3

##**6. Criando Modelos Finais *(Marts)* com dbt**

###6.1 - Staging para Participantes

In [29]:
%%writefile /content/pipeline_mulheres_na_tecnologia/models/staging/stg_participantes.sql
SELECT ID_PARTICIPANTE,
       NOME,
       PAIS_ORIGEM
FROM {{ source('dados_brutos', 'participantes') }}

Overwriting /content/pipeline_mulheres_na_tecnologia/models/staging/stg_participantes.sql

###6.2 - Staging para Países

In [31]:
%%writefile /content/pipeline_mulheres_na_tecnologia/models/staging/stg_paises.sql
SELECT "name.common" AS NOME_PAIS,
       cca3          AS CODIGO_PAIS,
       region        AS REGIAO
FROM {{ source('dados_brutos', 'paises') }}

Overwriting /content/pipeline_mulheres_na_tecnologia/models/staging/stg_paises.sql

###6.3 - Criando o modelo final (marts) - dim_desenvolvedoras

In [35]:
%%writefile /content/pipeline_mulheres_na_tecnologia/models/marts/dim_desenvolvedoras.sql

-- Configuração de materialização: vamos criar como uma tabela física.
{{config(materialized = 'table')}}

WITH stg_kaggle_survey_2022_mulheres_dados AS (
    SELECT * FROM {{ref('stg_kaggle_survey_2022_mulheres_dados')}}
),
stg_paises AS (
    SELECT * FROM {{ref('stg_paises')}}
)

SELECT stg_kaggle_survey_2022_mulheres_dados.PAIS,
       stg_paises.CODIGO_PAIS,
       stg_paises.REGIAO,
       stg_kaggle_survey_2022_mulheres_dados.NIVEL_EDUCACIONAL,
       stg_kaggle_survey_2022_mulheres_dados.ANOS_PROGRAMANDO,
       stg_kaggle_survey_2022_mulheres_dados.CARGO_ATUAL,
       stg_kaggle_survey_2022_mulheres_dados.ANOS_USANDO_ML,
       stg_kaggle_survey_2022_mulheres_dados.SALARIO_ANUAL_USD,
       stg_kaggle_survey_2022_mulheres_dados.LINGUAGENS_USADAS,
       stg_kaggle_survey_2022_mulheres_dados.BANCOS_DE_DADOS_USADOS,
       stg_kaggle_survey_2022_mulheres_dados.FERRAMENTAS_BI_USADAS
FROM stg_kaggle_survey_2022_mulheres_dados
   LEFT JOIN stg_paises ON stg_kaggle_survey_2022_mulheres_dados.PAIS = stg_paises.NOME_PAIS

Overwriting /content/pipeline_mulheres_na_tecnologia/models/marts/dim_desenvolvedoras.sql

###6.4 - Executando o dbt

In [36]:
!dbt run

20:30:39  Running with dbt=1.10.15
20:30:40  Registered adapter: sqlite=1.10.0
20:30:41  Found 6 models, 4 data tests, 4 sources, 416 macros
20:30:41
20:30:41  Concurrency: 1 threads (target='dev')
20:30:41
20:30:41  1 of 6 START sql table model main.my_first_dbt_model ........................... [RUN]
20:30:41  1 of 6 OK created sql table model main.my_first_dbt_model ...................... [OK in 0.11s]
20:30:41  2 of 6 START sql view model main.stg_kaggle_survey_2022_mulheres_dados ......... [RUN]
20:30:41  2 of 6 OK created sql view model main.stg_kaggle_survey_2022_mulheres_dados .... [OK in 0.08s]
20:30:41  3 of 6 START sql view model main.stg_paises .................................... [RUN]
20:30:41  3 of 6 OK created sql view model main.stg_paises ............................... [OK in 0.06s]
20:30:41  4 of 6 START sql view model main.stg_participantes ............................. [RUN]
20:30:41  4 of 6 OK created sql view model main.stg_participantes ........................ [OK in 0.05s]
20:30:41  5 of 6 START sql view model main.my_second_dbt_model ........................... [RUN]
20:30:42  5 of 6 OK created sql view model main.my_second_dbt_model ...................... [OK in 0.07s]
20:30:42  6 of 6 START sql table model main.dim_desenvolvedoras .......................... [RUN]
20:30:42  6 of 6 OK created sql table model main.dim_desenvolvedoras ..................... [OK in 0.06s]
20:30:42
20:30:42  Finished running 2 table models, 4 view models in 0 hours 0 minutes and 0.62 seconds (0.62s).
20:30:42
20:30:42  Completed successfully
20:30:42
20:30:42  Done. PASS=6 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=6

##**7. Orquestração e Monitoramento do Pipeline com Prefect**

In [37]:
# ==============================================================================
# CÉLULA COMPLETA: DEFINIÇÃO E EXECUÇÃO DO PIPELINE ORQUESTRADO
# ==============================================================================

# 1. Instalações
!pip install pandas prefect dbt-sqlite requests -q

# 2. Imports
import pandas as pd
import requests
import json
import sqlite3
from prefect import task, flow, get_run_logger
import subprocess
import os
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filename='pipeline.log',
    filemode='w'
)

logger = logging.getLogger()

print("Logging configurado com sucesso!")

# --- TAREFAS DE EXTRAÇÃO E CARGA (EL) ---
# Cada função de extração e carga que já construímos agora é uma @task do Prefect.

@task(retries=3, retry_delay_seconds=5)
def extrair_dados_kaggle(caminho_arquivo):
  try:
    logger.info(f"Inicando a extração do arquivo: {caminho_arquivo}")

    df = pd.read_csv(caminho_arquivo)

    logger.info(f"Extração do CSV concluída. {len(df)} linhas lidas e {len(df.columns)} colunas.")

    logger.info(f"Tipos de dados das colunas: \n{df.dtypes}")

    return df

  except FileNotFoundError:
    logger.error(f"Arquivo não encontrado: {caminho_arquivo}")
    return None
  except Exception as e:
    logger.error(f"Ocorreu um erro inesperado ao extrair os dados: {e}")
    return None

@task
def extrair_dados_sql(caminho_banco):
  try:
    logger.info(f"Inicando a extração do banco de dados: {caminho_banco}")

    conexao = sqlite3.connect(caminho_banco)

    query = "SELECT * FROM PARTICIPANTES"

    df = pd.read_sql_query(query, conexao)

    logger.info(f"Extração do banco de dados concluída com sucesso!")
    return df

  except sqlite3.Error as e:
    logger.error(f"Ocorreu um erro ao conectar ao banco de dados")
    return None
  except Exception as e:
    logger.error(f"Ocorreu um erro inesperado ao extrair os dados: {e}")
    return None

  finally:
    if conexao:
      conexao.close()
      logger.info("Conexão com o banco de dados fechada.")

@task
def extrair_categorias_habilidades_json(caminho_arquivo):
  try:
    logger.info(f"Iniciando a extração do arquivo JSON: {caminho_arquivo}")

    with open(caminho_arquivo, 'r') as arquivo:
      dados_json = json.load(arquivo)

    logger.info("Extração do JSON concluída com sucesso!")

    if dados_json is None:
      logger.warning("Dados JSON vazios. Nada a ser transformado")
    return None

    lista_categorias = []

    for categoria, habilidades in dados_json.items():
      for habilidade in habilidades:
        lista_categorias.append({"CATEGORIA": categoria, "HABILIDADE" : habilidade})

    df_categorias = pd.DataFrame(lista_categorias)

    logger.info("Transformação do JSON em DataFrame concluída com sucesso!")
    return df_categorias

  except FileNotFoundError:
    logger.error(f"Arquivo não encontrado: {caminho_arquivo}")
    return None
  except Exception as e:
    logger.error(f"Ocorreu um erro inesperado ao extrair os dados: {e}")
    return None

@task
def extrair_dados_paises_api(url_api):
  try:
    logger.info(f"Iniciando a requisição à API: {url_api}")

    resposta = requests.get(url_api)

    if resposta.status_code == 200:
      dados_json = resposta.json()
      logger.info(f"Dados da API extraídos com sucessos. {len(dados_json)} registros de países.")
      return dados_json
    else:
      logger.error(f"Falha na requisição à API. Código de status: {resposta.status_code}")
      return None

  except Exception as e:
      logger.error(f"Ocorreu um erro inesperado ao extrair os dados")
      return None

@task
def carregar_dados(df, nome_tabela, caminho_dw):
  if df is None:
    logger.warning("DataFrame vazio. Nada a ser carregado.")
    return

  try:
    logger.info(f"Iniciando o carregamento dos dados na tabela: {nome_tabela}")

    conexao_dw = sqlite3.connect(caminho_dw)

    df.to_sql(nome_tabela, conexao_dw, if_exists='replace', index=False)

    logger.info(f"Carga para a tabela '{nome_tabela}' concluída com sucesso!")

  except Exception as e:
      logger.error(f"Ocorreu um erro ao carregar os dados para a tabela '{nome_tabela}': {e}")

  finally:
    if conexao_dw:
      conexao_dw.close()
      logger.info("Conexão com o Data Warehouse fechada.")


# --- TAREFAS DE TRANSFORMAÇÃO (T) ---
# Tarefas que executam os comandos do dbt via terminal.

@task
def executar_dbt_run():
    logger = get_run_logger()
    logger.info("Iniciando 'dbt run'...")
    try:
        subprocess.run(['dbt', 'run'], check=True, cwd='/content/pipeline_mulheres_na_tecnologia')
        logger.info("'dbt run' concluído com sucesso.")
    except subprocess.CalledProcessError as e:
        logger.error(f"Falha no 'dbt run': {e}")
        raise

# --- O FLUXO PRINCIPAL (@flow) ---
# Orquestra a execução de todas as tarefas na ordem correta.

@flow(name="Pipeline ETL - Mulheres na Tecnologia")
def pipeline_principal():
    logger = get_run_logger()
    logger.info("### INICIANDO O PIPELINE DE ETL ###")

    # --- Fase 1: Extração e Carga (EL) ---
    # O Prefect executa estas tarefas em paralelo
    df_kaggle = extrair_dados_kaggle('/content/kaggle_survey_2022_mulheres_dados.csv')
    df_participantes = extrair_dados_sql('/content/bootcampBI.db')
    df_paises = pd.json_normalize(extrair_dados_paises_api("https://restcountries.com/v3.1/all?fields=name,cca3,region"))
    dados_habilidades = extrair_categorias_habilidades_json("/content/habilidades_categorias.json")

    # As cargas dependem das extrações (dependência implícita)
    carga_kaggle = carregar_dados(df_kaggle, 'kaggle_survey_2022_mulheres_dados', 'data_warehouse.db')
    carga_participantes = carregar_dados(df_participantes, 'participantes', 'data_warehouse.db')
    carga_paises = carregar_dados(df_paises, 'paises', 'data_warehouse.db')
    carga_habilidades = carregar_dados(dados_habilidades, 'categorias', 'data_warehouse.db')

    # --- Fase 2: Transformação (T) ---
    # A transformação com dbt só pode começar depois que TODAS as cargas terminarem.
    # Usamos 'wait_for' para criar essa dependência explícita.
    dbt_run = executar_dbt_run(wait_for=[carga_kaggle, carga_participantes, carga_paises, carga_habilidades])

    logger.info("### PIPELINE DE ETL CONCLUÍDO COM SUCESSO ###")

# --- EXECUÇÃO DO FLUXO ---
if __name__ == "__main__":
    pipeline_principal()

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-exporter-otlp-proto-http 1.37.0 requires opentelemetry-sdk~=1.37.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
google-adk 1.20.0 requires opentelemetry-api<=1.37.0,>=1.37.0, but you have opentelemetry-api 1.39.0 which is incompatible.
google-adk 1.20.0 requires opentelemetry-sdk<=1.37.0,>=1.37.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.39.0 which is incompatible.
Logging configurado com sucesso!

INFO:prefect:Starting temporary server on http://127.0.0.1:8098
See https://docs.prefect.io/v3/concepts/server#how-to-guides for more information on running a dedicated Prefect server.
INFO:prefect.flow_runs:Beginning flow run 'strict-chimpanzee' for flow 'Pipeline ETL - Mulheres na Tecnologia'
INFO:prefect.flow_runs:### INICIANDO O PIPELINE DE ETL ###
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Finished in state Completed()
WARNING:root:DataFrame vazio. Nada a ser carregado.
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.task_runs:Iniciando 'dbt run'...
INFO:prefect.task_runs:'dbt run' concluído com sucesso.
INFO:prefect.task_runs:Finished in state Completed()
INFO:prefect.flow_runs:### PIPELINE DE ETL CONCLUÍDO COM SUCESSO ###
INFO:prefect.flow_runs:Finished in state Completed()