<a href="https://colab.research.google.com/github/ingridcos/Exercicios-WoMakersCode/blob/main/Desafio_SQL_2_db.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3, pandas as pd

conn = sqlite3.connect('/content/DesafioSQL2.db.db')

In [2]:
tabelas = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;",
    conn
)
tabelas

          name
0    customers
1  order_items
2       orders
3     products

In [3]:
dfs = {}
for nome in tabelas['name']:
    dfs[nome] = pd.read_sql(f"SELECT * FROM {nome};", conn)

# exemplo: ver uma tabela específica
dfs['customers'].head()
dfs['order_items'].head()
dfs['orders'].head()
dfs['products'].head()

   product_id                nome  preco    categoria
0           1     Notebook Lenovo   3500  Eletrônicos
1           2  Smartphone Samsung   2500  Eletrônicos
2           3         Camisa Polo    120       Roupas
3           4          Tênis Nike    400       Roupas
4           5  Livro SQL Avançado     90       Livros

In [4]:
dfs['customers'].head()

   customer_id              nome               email dt_cadastro
0            1      João Pereira      joao@gmail.com  2024-01-10
1            2         Ana Souza       ana@yahoo.com  2024-02-15
2            3       Carlos Lima  carlos@hotmail.com  2024-03-05
3            4  Beatriz Oliveira     bia@outlook.com  2024-04-20
4            5      Pedro Santos     pedro@gmail.com  2024-05-01